spring.application.name=weple

server.port=8073

# DataSource : Oracle
# spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
# spring.datasource.url=jdbc:oracle:thin:@3.34.91.19:1521:xe
# spring.datasource.username=memo
# spring.datasource.password=memo

spring.datasource.driver-class-name=ENC(MG/WhWOoGGxWj7dGTgjnz7K1qbEoy4UL5PNfw+koRnD/wlXtLZ3qTNf6f7TcbkGoSedePHzv1TJH5z2wQL7IkQ==)
spring.datasource.url=ENC(/MNnSV3RsgNPVFtBexhNbPJ06FXvwSdIHqtYNRDm7vgaiHEQrf4fhk4HiuWxz1Pg/IotNadDZFSU/WUQfp+Iu+FnO/aQ04qB68pxEm3bHfo=)
spring.datasource.username=ENC(8Cq3RmcDm7Al6Zx0nZNMfSiw/ciTaF+fju3qsiKPLUSVGQ/WzIQoA5YGwU85mOmc)
spring.datasource.password=ENC(CYK0/cPHpSw6k8PqQXi3GqW35hDF7YrzTwo3ngUwJIIc3brOG1BP57vQOuchx+tb)

#Mybatis : Default Setting, Override
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.configuration.jdbc-type-for-null=NULL
mybatis.type-aliases-package=com.weple.cloud
mybatis.mapper-locations=classpath:mapper/**/*.xml

# logging
logging.level.com.weple.cloud=debug

#JPA Basic Setting
# SQL, Display
spring.jpa.show-sql=true
# SQL, Easy Reading
spring.jpa.properties.hibernate.format_sql=true
# No Vender DDL
spring.jpa.generate-ddl=true
# JPA Databalse Setting
spring.jpa.database=oracle


jasypt.encryptor.password=${JASYPT_PASSWORD}
