#S3
cloud.aws.credentials.access-key=ENC(4JZGE1DYHcMgBeECFZbkpHlqk7L5oiwVlkGsvwhtCJloHdeCbZ1/id7oAKcBvIxCP40OfTbQq1PpGr+lefWFbA==)
cloud.aws.credentials.secret-key=ENC(TUm52Qy4+IK+MX1F2PoHbmar6tutRh+UScKdYq6V+UnCMQfET5xm8K0Uuhk7di6exXG1SH2YmF7f9FnXkiunjc2MDPnt2o0QR+wdHnAN/+A=)
cloud.aws.region.static=ap-northeast-2
cloud.aws.s3.bucket=weple-cloud-files
