

server.port=${SERVER_PORT:80}

file.upload.task-dir=${FILE_UPLOAD_TASK_DIR:/uploadtest/tasks/}
file.upload.profile-dir=${FILE_UPLOAD_PROFILE_DIR:/uploadtest/profile/}


cloud.aws.credentials.access-key=${AWS_ACCESS_KEY_ID}
cloud.aws.credentials.secret-key=${AWS_SECRET_ACCESS_KEY}
cloud.aws.region.static=${AWS_REGION:ap-northeast-2}
cloud.aws.s3.bucket=${AWS_S3_BUCKET:weple-cloud-files}
